#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=1,walltime=0:10:00

tract=`jq -r '.tract' config.json`
type=`jq -r '.type' config.json`
new_param=`jq -r '.new_param' config.json`

echo "Resampling tck file..."
singularity exec -e docker://brainlife/dipy:0.14 python ./resampling_tract.py -tract $tract -type $type -new_param $new_param -out 'track.tck'

if [ -f 'track.tck' ]; then 
    echo "Resampling done."
else 
    echo "Resampling failed."
    exit 1
fi

echo "Complete"
