#!/bin/bash
#PBS -k o
#PBS -l nodes=1:ppn=1,walltime=0:10:00

tract=`jq -r '.tract' config.json`
step_size=`jq -r '.step_size' config.json`
subjID=`jq -r '._inputs[0].meta.subject' config.json`
run=`jq -r '.run' config.json`

echo "Resampling tck file..."
singularity exec -e docker://brainlife/dipy:0.14 python ./resampling_tract.py -tract $tract -step_size $step_size -out 'sub-'$subjID'_var-'${run}'_tract.tck'

if [ -f 'sub-'$subjID'_var-'${run}'_tract.tck' ]; then 
    echo "Resampling done."
else 
    echo "Resampling failed."
    exit 1
fi

echo "Complete"
